version: '3'
services:
  backend:
    image: node:15
    working_dir: /home/node/app
    volumes:
      - ./backend:/home/node/app
    ports:
      - "3001:3001"
    command: npm start

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/home/frontend
